In [1]:
import numpy as np

In [ ]:
mt = np.array([1,2,3,4,5])
print(type(mt))

mtfloat = np.array([1,2,3], dtype=np.float64)
print(type(mtfloat))

mtInt = np.array([1,2,3], dtype=np.int64)
print(type(mtInt))

mtNewInt = mt.astype(np.int64)
print(type(mtNewInt))

In [ ]:
#Gerando valores aleatórios
ale = np.random.rand(5)
print(ale)

dis_normal = np.random.randn(5)
print(dis_normal)

#Valores aleatporio numa matriz 3x4
matriz_ale = (10*np.random.random((3,4)))
print(matriz_ale)

[0.81813403 0.25805426 0.71009425 0.70065138 0.66574597]
[-1.09487434 -0.49639261  0.55719069  0.35154955 -1.23488213]
[[9.47256142 6.1344941  7.7355208  7.21102689]
 [6.41730345 6.73915739 9.93279979 8.87569107]
 [7.01199053 7.68699052 1.7214248  1.24047183]]


In [11]:
#Usando números aleatórios com semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

ale6 = gnr.integers(10, size = (3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [13]:
j = np.array([1,1,1,2,2,2,3,3,3,3,4,4,4,4,5,5])
print(j)
j = np.unique(j)
print(j)

[1 1 1 2 2 2 3 3 3 3 4 4 4 4 5 5]
[1 2 3 4 5]


In [15]:
k = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(k)
k = np.sqrt(k)
print(k)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
#extração de elementos 
k_linha_1 = k[0,:]
print(k_linha_1)

k_coluna_1 = k[:,0]
print(k_coluna_1)       

[1.         1.41421356 1.73205081]
[1.         2.         2.64575131]


In [18]:
#O exemplo abaixo é uma matriz 4x4
v = np.random.randn(4,4)
print(v)

x = (v > 1)
print(x)

z = np.where(v > 1, 1, 0)
print(z)

[[ 0.98382449  0.91824815 -1.50156347  0.48597448]
 [-0.06247607  1.3046136  -1.83255227 -0.67379562]
 [ 0.66157274  1.05440314 -0.46207701 -1.0544262 ]
 [ 0.58531231 -0.83800754  0.21998246  0.07596675]]
[[False False False False]
 [False  True False False]
 [False  True False False]
 [False False False False]]
[[0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]]
